name: HsRails
version: 1.3.0
description: High speed minecart rails
api-version: 1.14
main: no.netb.mc.hsrails.HsRails
commands:
  hsrails:
    description: Sets new minecart speed limit.
    usage: /hsrails <multiplier>
permissions:
  hsrails.cmd:
    description: Allows you to use speed cmd
    default: op