name: HsRails
version: 1.4.1
description: High speed minecart rails
api-version: 1.14
main: no.netb.mc.hsrails.HsRails
folia-supported: true
commands:
  hsrails:
    description: Sets new minecart speed limit.
    usage: /hsrails <multiplier>
permissions:
  hsrails.cmd:
    description: Allows you to use speed cmd
    default: op
